### PR TITLE
Blog Post: Caring For Bitcoin Core

### PR DESCRIPTION
**Pull request by Arvin21M**
**Build Preview:**

- [/blog/caring-for-bitcoin-core](https://os-website-git-caring-for-bitcoin-core-open-sats.vercel.app/blog/caring-for-bitcoin-core)

**Social Preview:**

- 
image

### CODE REVIEW

**Comment by Bayernatoor** [comment]
@Arvin21M ACK ... reviewed the post for grammar and links. Everything looks good from my side. 

One thing I noticed... is Furszy the same person as 0xB10C, this link points to Furszy's github ( I assume it's the same person? )

image

**Comment by Arvin21M** [comment]
Thanks @Bayernatoor, good catch! They are not the same person. Fixing now 🙏

**Review by dergigi — APPROVED** [review]
Looks good to me ✅

**Comment by dergigi** [comment]
It's live! 
- https://opensats.org/blog/caring-for-bitcoin-core
- [nostr post](https://njump.me/nevent1qqsfgk30d7694dcwp0rmy3fwume9927peyjlmhc03kr35wg8qpgshxspzemhxue69uhhyetvv9ujuurjd9kkzmpwdejhgqg5waehxw309aex2mrp0yhxgctdw4eju6t0qgs8suecw4luyht9ekff89x4uacneapk8r5dyk0gmn6uwwurf6u9rusenwh83)

**Pull request merged**
