### PR TITLE
Blog Post: Third Wave of Bitcoin Grants

### PR DESCRIPTION
**Pull request by dergigi**
Quick links:

- Build preview: [/blog/bitcoin-grants-december-2023](https://os-website-git-3rd-wave-bitcoin-grants-open-sats.vercel.app/blog/bitcoin-grants-december-2023)

Social Preview:

Screenshot 2023-12-18 at 14 35 00

### CODE REVIEW

**Review by Arvin21M — APPROVED** [review]
Checked all links and they appear to be loading and pointing to the right place. "Moisturized" LOL! Everything reads fine to me.

**Comment by Bayernatoor** [comment]
All links work, read through and everything looks great. Only feedback I have was in regards to the sentence below for the VLS grant. 

"The future support for multi-sig on the Lightning network that VLS will further improve security for users."

image

I'll go get moisturized now...

**Comment by dergigi** [comment]
Oh, nice catch @Bayernatoor! 

Feel free to suggest an edit directly here on GitHub in the [compare view](https://github.com/OpenSats/website/pull/197/files) and I'll incorporate it once I'm sitting in front of a computer again.

**Comment by dergigi** [comment]
Re-worded the VLS section, I think this is good to go now. 

Thanks for your reviews @Arvin21M @Bayernatoor 🙏🧡

**Pull request merged**
