### PR TITLE
Blog Post: LTS Grant for Bruno Garcia

### PR DESCRIPTION
**Pull request by dergigi**
To be sanity-checked by @OpenSats/volunteers 

**Build preview:**

- [/blog/bruno-garcia-receives-lts-grant](https://os-website-git-lts-bruno-open-sats.vercel.app/blog/bruno-garcia-receives-lts-grant)

**Social preview:**
Screenshot 2024-03-19 at 10 17 11

### CODE REVIEW

**Review by Bayernatoor — APPROVED** [review]
Looks good to me. Reads well and all links work. Second time I hear about this 90's "inflation fix" in Brazil this week!

Good work @cfunk7777

**Comment by Arvin21M** [comment]
Checked all hyperlinks, they work and point to the right place. 

Clearly states Bruno's accomplishments and why he is deserving of LTS.

Not 100% sure about the pants on the guy in the header image 🤣 

Nevertheless, great work ❤️

**Review by Arvin21M — APPROVED** [review]
Checked all hyperlinks, they work and point to the right place.

Clearly states Bruno's accomplishments and why he is deserving of LTS.

Not 100% sure about the pants on the guy in the header image 🤣

Nevertheless, great work ❤️

**Comment by btcschellingpt** [comment]
Looks good and reads well - all the links validated - good to go :-)

**Pull request merged**
