### PR TITLE
Update landing page

### PR DESCRIPTION
**Pull request by dergigi**
In short:

- Re-wrote copy
- Re-ordered sections
- Updated how the project card grid is displayed on mobile
- Full-width donate button styling on mobile & desktop
- Show latest 2 blog posts (instead of 5)
- Added "Why OpenSats" section on top

### CODE REVIEW

**Review by bitcoinprecept — APPROVED** [review]
I have reviewed it on Chrome on mobile and think the updates look FANTASTIC. The website really pops, looks clean, and grabs your attention. 

Scrolling through, the order and sizing of everything is great. 

The only personal nit pick if I'm forced to offer a constructive critique is that the font of the menu overlay feels different from the rest of the styling. 

Overall updates look wonderful and no bugginess encountered with any functionality clicking through sections. 

ACK

**Comment by Bayernatoor** [comment]
Looks great. I especially like the "Why OpenSats" section being there at the top. Reducing the posts to 2 makes sense as that front page realestate can be used to showcase some projects now.

I did make a video with some personal styling improvements I'd make, let me know what you think. 

https://github.com/OpenSats/website/assets/55212954/92f0c60a-a440-440f-a03d-ca7e285fda84

Changes made. 

Top subtitle font size: `2xl` --> `xl` 
Top section: remove `py` and `pb`
Stay updated: changed `pb` to `pb-2`
other sections: remove `pb`
bottom link: `View All Projects` changed pt to `pt-4`

**Comment by dergigi** [comment]
Thanks for the feedback! Glad I didn't make it worse 😂

@Bayernatoor I think your updates are fantastic, please create a separate PR to implement those details and cosmetic changes. We very much need someone with a keen eye to go over stuff, so thank you! 🙏🧡

**Comment by Bayernatoor** [comment]
Sounds good! I should have time to get to this tomorrow.

**Pull request merged**
