### PR TITLE
Add timeframe to email msg

### PR DESCRIPTION
**Pull request by dergigi**
We get this question sometimes, so it's useful to add this.

### CODE REVIEW

**Comment by Bayernatoor** [comment]
Looks wonderful!

**Review by bitcoinprecept — COMMENTED** [review]
This is good and an improvement. 

I might suggest offering them a communication channel to use to follow up after the 4 weeks if they haven't heard back yet.

**Review by Bayernatoor — APPROVED** [review]
Looks wonderful!

I second what @bitcoinprecept said regarding the communication channel - unless we're concerned that this made lead to too many emails/back and forth.

**Comment by dergigi** [comment]
Good call! Updated.

**Comment by dergigi** [comment]
Tested with https://github.com/OpenSats/applications/issues/545 - everything seems to work.

**Pull request merged**
