### PR TITLE
Add canary to /transparency

### PR DESCRIPTION
**Pull request by dergigi**
Heavily inspired by [Riseup's canary](https://riseup.net/about-us/canary).

---

Adds the following files and links:
- [opensats.org/canary](https://os-website-git-canary-open-sats.vercel.app/canary) (linked in [/transparency](https://os-website-git-canary-open-sats.vercel.app/transparency))
- [/docs/canary.txt](https://os-website-git-canary-open-sats.vercel.app/docs/canary.txt)
- [/docs/canary.txt.asc](https://os-website-git-canary-open-sats.vercel.app/docs/canary.txt.asc)

### CODE REVIEW

**Comment by 0xB10C** [comment]
It probably makes sense to GPG sign this canary and have it expire after a few month. In its current form it isn't useful, as you'll likely be forbidden to update it if a three letter agency knocks.

**Comment by dergigi** [comment]
Yeah, I figured. Thanks for the feedback. Will make adjustments accordingly.

**Review by Arvin21M — APPROVED** [review]
- Link works. 
- Steps to verify seems simple enough. 
- Not a show stopper but the top of the page could benefit from a short sentence or two describing what this is for, for the less technically inclined visitor. 
- Also not a show stopper, but Canary is short for Warrant Canary. Consider calling it Warrant Canary?

Otherwise..... Good to go! 🚀

**Comment by Bayernatoor** [comment]
Everything works on my end as well.

Imported the sig and verified the canary file. Looks good to me.

image

May want to consider adding a step on how to import a gpg key.

1. Copy the entire public key block into a txt file
2. Run `gpg --import [file_name].txt`

Or the key could also be stored on the website as a txt file and we can provide a `wget` command to automatically download it.

**Comment by abitcoinperson** [comment]
This is great

**Pull request merged**
