### PR TITLE
Blog Post: Fourth Wave of Nostr Grants

### PR DESCRIPTION
**Pull request by dergigi**
To be reviewed by @nvk and sanity-checked.

**Build preview:** 

- [/blog/nostr-grants-december-2023](https://os-website-git-4th-wave-nostr-open-sats.vercel.app/blog/nostr-grants-december-2023)

**Social preview:**

Screenshot 2023-12-21 at 00 43 41

### CODE REVIEW

**Review by Arvin21M — APPROVED** [review]
All the links point to the correct URL. All the content reads fine to me. Noticed an upper case 'N" for Nostr under the Flockstr description, whereas everywhere else its lower case. Did not earmark for edit. Otherwise super excited watching Nostr projects flourish. 🚀

**Comment by bitcoinprecept** [comment]
Added minor comment

"A year of experimentation, a year of relaying, a year of building other stuff." is technically not a sentence. Would suggest:

It's been a year of experimentation, a year of relaying, and a year of building other stuff.

Also concur on normalizing whether Nostr is a capitalized proper noun or not.

**Comment by Bayernatoor** [comment]
Read and Reviewed. Looks good to me.

**Comment by dergigi** [comment]
Thanks for the reviews guys. Fixed! 

Let's get this baby shipped :shipit:

**Comment by dergigi** [comment]
Live here: https://opensats.org/blog/nostr-grants-december-2023

**Pull request merged**
