### PR TITLE
Blog Post: Long-Term Support For Hodlbod

### PR DESCRIPTION
**Pull request by dergigi**
**Build preview:**

- [/blog/hodlbod-receives-lts-grant](https://os-website-git-hodlbod-lts-open-sats.vercel.app/blog/hodlbod-receives-lts-grant)

**Social preview:**

- 40-hodlbod-thumb

### CODE REVIEW

**Comment by staab** [comment]
If we could tweak the language:

"It supports various NIPs to enable features like social threads, customizable feeds, Lightning Zaps, and multiple user accounts." -> "Coracle has been the test bed for several innovations to nostr, including private groups, new-style DMs, and custom feeds."

"He also created [Triflector](https://github.com/coracle-social/triflector), a nostr relay enforcing authentication via custom policies. Triflector supports access control methods like pubkey whitelisting, dynamic policy checks, relay claims, and group-based controls with [NIP-87](https://github.com/coracle-social/nips/blob/groups/87.md)." -> "He has also created a number of other projects, including [Triflector](https://github.com/coracle-social/triflector), a nostr relay enforcing authentication via custom policies; [Welshman](https://github.com/coracle-social/welshman), a library providing functionality extracted from Coracle; and [Keypub](https://keypub.coracle.social/), an experimental feed focused on people rather than notes.

"With this grant, Hodlbod plans to continue enhancements of Coracle and Triflector, while expanding his efforts across several key areas, including:" -> "With this grant, Hodlbod plans to continue development of Coracle and his experimentation, focusing on certain key areas:"

Then for the bullets,

- Refining Coracle's user experience and releasing native versions.
- Using DVMs and special purpose relays to support more use cases in a decentralized way.
- Researching ways to improve interoperability to advance nostr's growth.
- Researching applications and implementations of web of trust to reduce spam, improve privacy, and recommend content.

**Comment by dergigi** [comment]
Thanks for the review @staab - we'll make the adjustments accordingly.

**Comment by Arvin21M** [comment]
Ready for @OpenSats/volunteers sanity review 🙏

**Comment by dergigi** [comment]
I'll get this out today, unless you have any other edits @staab 🙏

**Review by Arvin21M — APPROVED** [review]
Links all working and pointing to correct destination. Hodlbod review complete. Hodlbod change requests implemented. Good to go 🚀

**Comment by staab** [comment]
Oh, one other thing, I am not the host of tgfb, just tgfn.

**Comment by Arvin21M** [comment]
> Oh, one other thing, I am not the host of tgfb, just tgfn.

@staab Co-Host for TGFN or Host?

**Comment by staab** [comment]
Co-host is good

**Review by Arvin21M — APPROVED** [review]

**Comment by cfunk7777** [comment]
> Ready for @OpenSats/volunteers sanity review 🙏 

- Read it backwards, no typos found

**Comment by dergigi** [comment]
It's live! Thanks everyone 🙏🧡

**Pull request merged**
