### PR TITLE
Canary v3

### PR DESCRIPTION
**Pull request by dergigi**
**TODO:**

- [x] Update block height & hash
- [x] Re-sign at the beginning of November

Build preview:

- [/canary](https://os-website-git-canary-v3-open-sats.vercel.app/canary)

---

Minor updates/improvements:

- Use block hash instead of article
- Link to [keybase.io/verify](https://keybase.io/verify) as an alternative to CLI

### CODE REVIEW

**Comment by dergigi** [comment]
Ready for review 👀 

(Tagging @Bayernatoor because I think you reviewed it the last time)

**Comment by btcschellingpt** [comment]
1. On the /canary link, the text shown is truncated by a few letters. Better if this can be wrapped/presented so there is no doubt precisely what is written
2. On the Vercel Preview .. dafuq is the canary? I poked around through all the pages (I think) and cannot find the canary

**Comment by dergigi** [comment]
Build preview link in the description links directly to the canary:

---

Build preview:

- [/canary](https://os-website-git-canary-v3-open-sats.vercel.app/canary)

---

The [/transparency](https://os-website-git-canary-v3-open-sats.vercel.app/transparency) page links to it.

**Comment by dergigi** [comment]
Re (1) - text isn't truncated I believe, you can horizontally scroll.

**Comment by ecurrencyhodler** [comment]
@btcschellingpt based on the text, it's meant to signal to the bitcoin community that opensats has been compromised. If they don't publish a new signature based on the cadence provided, then we can assume opensats has been compromised.

**Review by ecurrencyhodler — APPROVED** [review]
Tested on mobile and desktop. I can confirm the box is scrollable both on desktop and mobile to the right and left. 

LGTM.

I haven't tested the signature however.

**Comment by dergigi** [comment]
I tested the signature with CLI and with keybase. :shipit:

**Comment by btcschellingpt** [comment]
I have also verified the signature by CLI and using Keybase - good to go.

**Pull request merged**
