### PR TITLE
Add `/blog`

### PR DESCRIPTION
**Pull request by dergigi**
Very simple dummy blog for now (to get the announcement out). Will improve it in due time (before the 2nd blog post is published).

Preview: [opensats.org/blog](https://opensats-git-blog-paulteam.vercel.app/blog)

### CODE REVIEW

**Comment by jamesob** [comment]
Great. Code looks good, will try to test locally today. 

Note for other reviewers: doesn't look like CI automatically deploys to the live infra (based on contents of https://github.com/OpenSats/website/blob/master/.github/workflows/build.yml).

**Review by nvk — CHANGES_REQUESTED** [review]
The text still ipsum loren

**Comment by dergigi** [comment]
@jamesob not sure what you mean regarding deployment?

We've deployed [a lot of changes](https://github.com/OpenSats/website/pulls?q=is%3Apr+is%3Aclosed) in the last couple of days. Both `Preview` and `Production` are working fine.

**Comment by jamesob** [comment]
@dergigi what I mean is that, as far as I can tell, merging does not trigger an automatic deployment. But I could be wrong!

**Review by modl21 — COMMENTED** [review]
onwards

**Pull request merged**
