### PR TITLE
Blog Post: jb55 LTS

### PR DESCRIPTION
**Pull request by dergigi**
Build preview:

- [/blog/jb55-receives-lts-grant](https://os-website-git-jb55-lts-open-sats.vercel.app/blog/jb55-receives-lts-grant)

Social preview:
- 35-jb55

### CODE REVIEW

**Comment by dergigi** [comment]
Ready for review by @OpenSats/volunteers

**Review by Arvin21M — APPROVED** [review]

**Comment by Bayernatoor** [comment]
Read and reviewed. All links work and reads well. Nice post @Arvin21M @dergigi

**Comment by btcschellingpt** [comment]
Read and reviewed - all links working and good to go! Fuck yeah! DaMoose .. love it :-D

**Review by btcschellingpt — APPROVED** [review]
Checked all links, reviewed post and art - quality :-)

**Pull request merged**
