### PR TITLE
Remove unused and superfluous fields from application form

### PR DESCRIPTION
**Pull request by dergigi**
Changes:

- Remove keywords, as they are unused according to code and @abitcoinperson 
- Merge "short description" and "long description (optional)" into "project description"

### CODE REVIEW

**Comment by dergigi** [comment]
Test application on Vercel succeeded & application was received.

**Comment by h4rpr** [comment]
i agree keywords should go, but the short description is displayed on a projects "avatar" on the projects page, and the long becomes visible after clicking on a specific project. think this will add a step for us.

**Review by h4rpr — COMMENTED** [review]
i agree keywords should go, but the short description is displayed on a projects "avatar" on the projects page, and the long becomes visible after clicking on a specific project. think this will add a step for us.

**Comment by dergigi** [comment]
I am aware of that. Given that projects are added manually by us, we can trim the description as we see fit.

We shouldn't offload this additional work to applicants.

**Comment by dergigi** [comment]
I will merge this now. Will take full responsibility in case something breaks.

**Pull request merged**
