### PR TITLE
Fix line jump with animated text

### PR DESCRIPTION
**Pull request by Bayernatoor**
This resolves: https://github.com/OpenSats/website/issues/324.

1. Typed comp will be on a new line if device screen is mobile or tablet
2. Update font size of headers on homepage.

### CODE REVIEW

**Review by dergigi — APPROVED** [review]

**Comment by dergigi** [comment]
Awesome! Thanks for taking care of that @Bayernatoor 🙏🧡

Looks good to me ✅

**Comment by Arvin21M** [comment]
@Bayernatoor and @dergigi 
Checked on mobile and the typed comp is on a new line now, which is great, however the one for **"Open-Source Projects"** still jumps, as it creates a third line to compensate for the space needed on the "S" for Projects.

**Comment by Bayernatoor** [comment]
> @Bayernatoor and @dergigi Checked on mobile and the typed comp is on a new line now, which is great, however the one for **"Open-Source Projects"** still jumps, as it creates a third line to compensate for the space needed on the "S" for Projects. 

Bah I thought I checked all breakpoints. What phone do you have? We'll likely have to reduce the font size further for that size screen. 

I'll take a look tomorrow.

**Comment by Arvin21M** [comment]
The phone in this screenshot is iPhone SE.

One of the words in the rotation we already have is "FOSS" which covers the open-source partly. Maybe we change it to just say Support "Projects" instead? @dergigi Any thoughts on this?

**Comment by Bayernatoor** [comment]
> The phone in this screenshot is iPhone SE.
> 
> One of the words in the rotation we already have is "FOSS" which covers the open-source partly. Maybe we change it to just say Support "Projects" instead? @dergigi Any thoughts on this?

All good I'll review it and get it working properly tomorrow am just gotta change font sizes on the smaller breakpoints!

**Comment by dergigi** [comment]
> Any thoughts on this?

Get a bigger phone! 😝😂

**Comment by Arvin21M** [comment]
> Get a bigger phone! 😝😂

Now I regret asking.
image

**Pull request merged**
