### PR TITLE
Make budget mandatory in application form

### PR DESCRIPTION
**Pull request by dergigi**
This will make our lives easier.

### CODE REVIEW

**Comment by dergigi** [comment]
Tested & looks good to me ✅

**Comment by nvk** [comment]
👍

**Comment by dergigi** [comment]
Please ACK properly @nvk so I can press the button

Screenshot 2023-05-05 at 20 28 38

**Review by jamesob — APPROVED** [review]

**Comment by nvk** [comment]
ACK, properly

**Pull request merged**
