### PR TITLE
Blog Post: Third Wave of Education Grants

### PR DESCRIPTION
**Pull request by Arvin21M**
**Build Preview:**

- [/blog/3rd-wave-of-education-grants](https://os-website-git-3rd-wave-education-open-sats.vercel.app/blog/3rd-wave-of-education-grants)

**Social Preview:**

- 
image

### CODE REVIEW

**Comment by Arvin21M** [comment]
@OpenSats/volunteers team, please have a quick glance as a sanity check to uncover any last minute items for correction that may have been missed previously 🙏

**Comment by Bayernatoor** [comment]
@Arvin21M Read and reviewed, all links are correct. No suggestions or corrections to make.

**Review by Bayernatoor — APPROVED** [review]
@Arvin21M Read and reviewed, all links are correct. No suggestions or corrections to make.

**Comment by dergigi** [comment]
Live now!
- [nostr post](https://njump.me/nevent1qqsx4frlhdmnwn59nhl5qqksk2tmlkllnx3wjkd24sscdey8u85r6dcpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqgdwaehxw309ahx7uewd3hkcq3q0pensatlcfwktnvjjw2dtem38n6rvw8g6fv73h84cuacxn4c28eqmlfc9p)
- https://opensats.org/blog/3rd-wave-of-education-grants

**Pull request merged**
