### PR TITLE
v2

### PR DESCRIPTION
**Pull request by dergigi**
v2 of the website

### CODE REVIEW

**Comment by abitcoinperson** [comment]
found a couple of typos on Dread's page

**Comment by abitcoinperson** [comment]
Dropping in feedback given from the volunteer chat (credit to Gabe): 

Mission Page:
No links, the only way to get off this page is hitting the back button or one of the menu buttons at the top. At the very least link the “Donate to OpenSats” button.

Apply Page
•Grant Selection Process doesn’t link
•Seems hard to actually get to  the application step. The “our programs” seems too low on the page 

Project Page:
•Project name should be clickable
•implement a tag system for projects. To see what I want to donate to I have to read each description. If I want to just filter for privacy focused projects I should be able to.

FAQ
•collapse content on this page, clicking should expand to show the answer. I shouldn’t have to scroll through all FAQ answers to find mine

**Comment by abitcoinperson** [comment]
I'd also add:

**Home Page / All Pages:** 

- Navigation Options (About, Mission, Etc.) disappears on mobile and small web view. Maybe hamburger menu would be a good option
Screenshot 2023-06-21 at 5 51 39 PM
Screenshot 2023-06-21 at 5 51 50 PM

**/apply page:**

- Under the general grant section, do we perhaps want to mention nostr? Not sure if we should maybe segment nostr fund from general fund, but probably needs discussion
Screenshot 2023-06-21 at 5 52 47 PM

**Comment by abitcoinperson** [comment]
- logos are annoyingly not fit to the right size (but I'm sure you know that) 
- it's exacerbated at weird medium width screen size
image
image

**Comment by abitcoinperson** [comment]
Lastly, the logo / icon on the top right of everyscreen isn't really our logo

>_OpenSats        not           >_     OpenSats

I'm not in love with the color choices etc for our existing logo fwiw, but I do like that when the "O" is close to ">_" it makes a little winky face ">_O" lol

image
image

**Comment by nvk** [comment]
Make them 50% of the size of the square. Always on the middle.

**Comment by abitcoinperson** [comment]
tested fiat donations, which seem to work. A couple of nits:

1. The arrows on the far right of the custom input text box for donation amount is quite strange on web and mobile
2. We don't allow fiat donations under $1.00 (the form just won't submit if you enter something like $0.50... which I think is okay)
3. The navigation arrows allow for negative amounts to be input, which is strange, but the actual Stripe donation page doesn't open, so I think this is okay for now
4. We should add a subscription toggle (which has been mentioned in another issue)
5. For fiat donations over a few hundred bucks, its preferable if they simply wire or ACH us money... perhaps we have some sort of callout or information about this. (Right now we will pay about 3% of donations via Stripe. So for something like a $1000 payemnts, thats a decent amount. And for something like $10,000 is quite significant
6. In the past, we had companies which were going to pick up the payment processing, but have not arranged that or confirmed that lately. We should:
- either find sponsors who will match donations up to 3-4% for processing fees. 
- ask the donor if they are willing to cover the processing fees
- just eat the fees ourselves.... 

We might need to update /FAQ page which implies that credit card fees are also picked up 
image

**Comment by abitcoinperson** [comment]
It should be noted that I'm happy to help with some of the payment processing fees moving forward at TBC, but we are pretty poor so might wanna find other people / companies to help with that.

**Pull request merged**
