### PR TITLE
Add /funds URL and fix broken links via redirects

### PR DESCRIPTION
**Pull request by dergigi**
New:
- [/funds](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/funds)
- [/funds/general](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/funds/general)
- [/funds/nostr](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/funds/nostr)
- [/funds/ops](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/funds/ops)
- [/projects/showcase](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/showcase)

Redirects:
- [/projects => /funds](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects)
- [/projects/nostr => /funds/nostr](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/nostr)
- [/projects/general_fund => /funds/general_fund => /funds/general](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/general_fund)
- [/projects/opensats_operations_budget => /funds/opensats_operations_budget => /funds/ops](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/opensats_operations_budget)
- [/projects/all => /projects/showcase](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/showcase)

This should fix all broken links.

### CODE REVIEW

**Comment by dergigi** [comment]
@Arvin21M please click around in the [build preview](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/) to see if anything is broken, especially around the paths and redirects mentioned in the PR description. Thank you 🙏

**Comment by Arvin21M** [comment]
### **Check Completed**
- @dergigi I reviewed build preview a couple of times. 
- Majority of broken links will be corrected with the new links and redirects you mentioned above.
- See below for possible additional fixes.

### **Project Listing areas of concern that may need more attention:**

- Projects without a direct donate button on their respective pages. 
- This is okay?
-- [Stratum V2](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/stratumv2)
-- [Amethyst](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/amethyst)
-- [Bitcoin Dev Kit](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/bdk)
-- [Bitcoin Core](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/bitcoin-core)
-- [Splicing](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/splicing)

### **Twitter Link broken for project [Bitcoin Core](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/projects/bitcoin-core):**

- Twitter icon needs to be directed to https://twitter.com/bitcoincoreorg
-- Currently >> Twitter Icon > https://twitter.com/undefined says **"ACCOUNT SUSPENDED"**

### **Matt Odell [bio page](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/about/odell):** 

- Remove Twitter handle? 
- Twitter icon directs to message "[**ACCOUNT DOESNT EXIST**](https://twitter.com/ODELL)."

### **Blog Article Broken Links on Build Preview:**

- [Long-Term Support For René Pickhardt](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/blog/rene-pickhardt-receives-lts-grant)
-- Currently >> "[René Pickhardt](https://ln.rene-pickhardt.de/)" hyperlink says **"SERVICE UNAVAILABLE"**
- [Third Wave of Bitcoin Grants](https://os-website-git-forwards-to-fix-dead-links-open-sats.vercel.app/blog/nostr-grants-october-2023) for NOSTUR
--  Currently >> Nostur "[mission](https://blogstack.io/naddr1qq8xummnw36hyttdd9ehx6t0dcq3gamnwvaz7tmjv4kxz7fwv3sk6atn9e5k7q3qn0sturny6w9zn2wwexju3m6asu7zh7jnv2jt2kx6tlmfhs7thq0qxpqqqp65w8jxczy)" hyperlink says **"SITE CANT BE REACHED"**

**Review by Arvin21M — APPROVED** [review]
Great! New links/redirects look like it will fix just about everything. 
Please refer to my recent comment about other possible fixes, if even necessary.

**Comment by dergigi** [comment]
Thanks! Moved the other stuff you've found to a separate issue, see https://github.com/OpenSats/website/issues/249 - the project pages will probably change again soon so I removed that part.

**Pull request merged**
