### PR TITLE
Blog Post: Long-Term Support For Yuki

### PR DESCRIPTION
**Pull request by dergigi**
To be sanity checked by @OpenSats/volunteers 

---

**Build preview:**

- [/blog/yuki-receives-lts-grant](https://os-website-git-yuki-lts-open-sats.vercel.app/blog/yuki-receives-lts-grant)

**Social preview:**

37-yuki

### CODE REVIEW

**Comment by Bayernatoor** [comment]
:rofl:  my rusty joke was removed... I guess it itself was kinda rusty.

**Comment by Arvin21M** [comment]
@dergigi looks like we have the go-ahead from @yukibtc (thanks Yuki!) on this draft with no change requests.

**Review by Arvin21M — COMMENTED** [review]
Links work. Looks good to me.

**Comment by dergigi** [comment]
Live now! 

- https://opensats.org/blog/yuki-receives-lts-grant
- nostr: [https://njump.me/nevent1qqsyxn...](https://njump.me/nevent1qqsyxn8cdkfn4pcpt8le8h4p9fm95d0p6rqf8tw94ur4qnxhm6q5vwqzypu8xwr40lp96ewdj2fef408wy70gd3carf9n6xu7hrnhq6whpglymh0d80)

**Pull request merged**
