### PR TITLE
Blog Post: Doubling Down on Nostr

### PR DESCRIPTION
**Pull request by Arvin21M**
**Build Preview:**

- [/blog/doubling-down-on-nostr](https://os-website-git-nostr-double-down-open-sats.vercel.app/blog/doubling-down-on-nostr)

**Social Preview:**

- 
image

### CODE REVIEW

**Comment by Arvin21M** [comment]
All of the links and donate button in working order.

**Comment by Arvin21M** [comment]
@dergigi & @OpenSats/volunteers 
Please have a read for a sanity check and anything I may have missed. 
Otherwise, ready to ship :shipit:

**Review by dergigi — APPROVED** [review]
Looks good to me ✅

**Comment by dergigi** [comment]
Live now!
- https://opensats.org/blog/doubling-down-on-nostr
- [nostr post](https://njump.me/nevent1qqsw22ankwkhjn252l5hj4dr026elst5flr2sl8f4m7rtp3d44x0wjgpzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgq3q0pensatlcfwktnvjjw2dtem38n6rvw8g6fv73h84cuacxn4c28eqns2nv4)

**Pull request merged**
