### PR TITLE
Add `core` tag to Jon Atack's LTS announcement

### PR DESCRIPTION
**Pull request by Arvin21M**
Add `core` tag to Jon Atack's LTS announcement

### CODE REVIEW

**Comment by jonatack** [comment]
SGTM. Didn't look, but if "BIPs" is a tag, can add it too.

**Comment by jonatack** [comment]
Related: https://github.com/OpenSats/website/pull/368#discussion_r1870239471

**Comment by dergigi** [comment]
> Feel free to add me to the developers in the "core" page at https://opensats.org/tags/core to keep them in sync.

The tag will do that automatically, so that's taken care of: https://os-website-git-arvin21m-patch-2-open-sats.vercel.app/tags/core

**Comment by jonatack** [comment]
> The tag will do that automatically

Nice 👍

**Pull request merged**
