### PR TITLE
Add "project website" to general application form

### PR DESCRIPTION
**Pull request by dergigi**
Small adjustment to application form, as requested by education committee.

### CODE REVIEW

**Comment by dergigi** [comment]
Tested using build preview, all 3 variations of applications that I tried worked. I'm confident that this won't break anything and will go ahead and merge this (famous last words, I know).

**Comment by Bayernatoor** [comment]
@dergigi I'll be back at my desktop in about 1 hour, I'll review it then if still necessary.

**Review by Bayernatoor — APPROVED** [review]
Everything looks good on my end. I submitted 2 general apps and 1 LTS app and had no issues. @dergigi Do you see them on GH and did the new fields get added? 

Can also confirm that I received all 3 email confs.

Also, I only know of the 2 methods to apply via: https://os-website-git-add-other-links-to-gh-open-sats.vercel.app/apply#criteria  what's the third?

**Comment by dergigi** [comment]
> Do you see them on GH and did the new fields get added?

Yes!

Thanks for testing 🙏

**Pull request merged**
